### ISSUE TITLE
Recommended approach for global rules?

### ISSUE THREAD

**Issue by doctyper** [martinandert/react-inline#1]
Very nice framework. I'm considering switching over from Radium. I'm curious if you have a recommendation for how to handle things like [CSS Resets](http://meyerweb.com/eric/tools/css/reset/) and/or @font-face rules.

For comparison, Radium provides a [Style component](https://github.com/FormidableLabs/radium/tree/master/docs/api#style-component) to write raw CSS rules.

**Comment by martinandert** [comment]
I recommend using an extra css file for global styles, as I am doing it in the example (see [example/public/](https://github.com/martinandert/react-inline/tree/master/example/public) and [example/views/layout.ejs](https://github.com/martinandert/react-inline/blob/master/example/views/layout.ejs).

One of React Inline's goals is to be easy to use and therefore it is rather strict concerning functionality. I think handling global css rules is out of the library's scope. But that does not mean that I am not open for good ideas on how to extend/improve things.
