### ISSUE TITLE
How well does it work with hot module replacement?

### ISSUE THREAD

**Issue by chcokr** [martinandert/react-inline#2]
Thanks for your hard work. Sorry for being lazy, but I was wondering how well this library works with Webpack's hot module replacement. For example, Webpack's style-loader works with HMR out of the box.

Again, I should really try this out myself, but I'm really busy, so I'm just asking here. Thanks for your time.

**Comment by martinandert** [comment]
I have never used Webpack's hot module replacement, but theoretically it should be possible b/c react-inline's extractor binary runs before webpack. Just run react-inline-extract with the `--watch` option and set webpack's source dir to the output dir configured for react-inline-extract.

Please re-open if this didn't help you.
