### ISSUE TITLE
Update readme.md file

### ISSUE THREAD

**Issue by mairh** [martinandert/react-inline#5]
`import cx from 'classnames'` has been depreciated and react does not bundle classnames package implicitly. You have to import classnames as a separate add-on package [link here](https://www.npmjs.com/package/classnames)

**Comment by martinandert** [comment]
Well, doing `import cx from 'classnames'` is actually referring to the separate add-on package you mention. It's just stored in a variable named `cx`.

Feel free to re-open this issue if this doesn't solve it for you.
