### ISSUE TITLE
Out of date documentation

### ISSUE THREAD

**Issue by sheerun** [martinandert/react-inline#6]
Given your exports, one should import react-inline in following way:

```
import { create } from 'react-inline'
```

It's because you don't do `export default` in StyleSheet.js

**Comment by mjohnston** [comment]
The transformer looks for a `StyleSheet.create` expression so you can't use a destructuring import here.  The docs mention this [here](https://github.com/martinandert/react-inline#stylesheetcreatespec).

That being said, the stub StyleSheet module should probably use a default export to avoid confusion.

**Comment by sheerun** [comment]
Probably yes, because I get an error when I try to import it the way documentation says to :) (ES6)

**Comment by martinandert** [comment]
@sheerun What error do you get when trying to import?

Is there any action I need to take to make things better?

**Comment by martinandert** [comment]
In v0.6.4, `export default` has been added to StyleSheet.js.
